### ISSUE TITLE
Desktop UX/UI:  October launch essentials 🚀

### ISSUE THREAD

**Issue by dominijk** [colouring-cities/colouring-core#299]
Top priority is user UX flow. Collection of UX issues from various conversations, roughly in priority order. 

- [x] sign up issues #44 
- [x] Copy all/some (toggles tick box) | Copies multiple fields #283 
- [x] view and edit process #298
- [x] Set up expand/collapse under planning #300 
- [x] Set up expand/collapse under size/shape #237
- [ ] Size and shape fields #117 
- [ ] Construction fields #168 
- [ ] Age fields #208 
- [ ] Decade selector for age #151 
- [ ] Feature and introductory videos with GIF for social media #336 
- [ ] Last edit time and author as part of verification process  #269 
- [ ] Verification button | Allows user to verify other user data #199 
- [ ] Alert button | Menu as twitter > spam / malicious /   #284
- [ ] colour all fields #367
- [ ] Merge demolitions category into age #266 
- [x] Add colouring London logo to top of page (move cycling colour logo) 
- [ ] Add colouring London logo to key 
- [ ] Add copyright to bottom of key 
- [x] Add data accuracy disclaimer box to map page #277 
- [ ] Test locations for switch theme button, rename to day/night

**Comment by dominijk** [comment]
Ready fo launch :rocket:
