### ISSUE TITLE
Bulk Data: Update height data

### ISSUE THREAD

**Issue by dominijk** [colouring-cities/colouring-core#548]
Links to [analysis](https://github.com/colouring-london/colouring_london_analysis/blob/master/bulk_extracts/ucl_bseer_3d_stock_extract.md) and #543 

- [x] 1. Extract data from UCL Energy - see #556 wiith issue on missing matches
- [x] 2. Check the extract against our database 
- [x] 3. Upload the data into our database (took 16+ hours to run) 
- [ ] 4. Amend our database structure to include constraint as #550 
- [x] 5. Add a height source to the website as #434 
- [ ] 6. Front end edit to relabel height from `Height to apex` to `Height to apex (tallest point)`  #434 
- [ ] 7. Function to generate a liner colour gradient for buildings based on the min and max
- [x] 8. Front end edit to change category visualisation from storeys to height (raise new issue) 
- [x] 9. Front end edit to change the map legend for the category (same new issue)

**Comment by dominijk** [comment]
See https://github.com/tomalrussell/colouring-london/pull/551 @mz8i Minor tweak on this is point 6 above and waiting review and confirmation by @polly64 on point 7

**Comment by polly64** [comment]
Linear gradient good

**Comment by tomalrussell** [comment]
Colours look good, but there is an overlap in the ranges: values first increase up to '5.55-7.73', then '7.73-1.138' looks wrong, and then continue on up from 1.138.

Could be a typo with the decimal point, or doubled up on options for the lower part of the height range?

**Comment by mz8i** [comment]
Sorry about that, in the rush yesterday I just took the scale from #434 description and didn't check the values... @dominijk what should be the correct scale?
