### ISSUE TITLE
UI: Activate construction category & land use 

### ISSUE THREAD

**Issue by dominijk** [colouring-cities/colouring-core#568]
References #359 #361 

Below steps are taken from the [docs](https://github.com/tomalrussell/colouring-london/blob/master/docs/adding-new-fields.md) for how we add a new category.  Map will be coloured by primary material.  

- [ ] Set up database, adding primary material ,roof material and secondary materials using material options as #539 with constraint (entry on website is drop down)
- [ ] Set up API elements
- [ ] Set up front end, entry is drop down for primary material ,roof material and secondary materials 
- [ ] Set up data extracts
- [ ] Setup tile server - colours for map tiles as #539 
- [ ] Set up legend 
- [ ] Add bulk data set see [issue](https://github.com/colouring-london/colouring_london_analysis/issues/18)

**Comment by polly64** [comment]
@tomalrussell Interface really starting to look great. Will put all comments below.

Main interface page
1. On my computer the  4x3 logo is turning into a 3x4- can we do something to make it stay the same as menu  one
2) I agree if menu can collapse so u can see map before would be good but needs to be really clear as to where it's gone.  I really like way menu says menu and has menu logo. Everything just needs to be super clear- I think though that this should go in to next to do list and we shouldn't wait for this to release.
2. When u click on a category a coloured category title comes up.  I think this clashes a bit with the logo and it would be better to  a) keep a highlight around the selected  category on the 12box logo (say in thick light grey or possibly turquoise as on menu) and b) have a white rather than a coloured background for the category title with a thin border (same as grey border on box below). Also have   this title box align with left hand side of 12 box logo/categories  and match the width and alignment of data entry boxes below.  

Materials
1. Can we upload melda's listed buildings as also will be useful re showing for grant (esp as we have have to rethink approach to designation)
2. Can we swap the colour allocated for' wood' for the colour allocated for 'other natural material'? as the wood colour i realise is going to be quite dark and unsatisfying to colour in- the brick , steel and RC colours are really nice to use.
3. I really like the way the copy tool is so clearly marked now, My only thought is i think there is  one too many steps and it's not quite intuitive yet.  So it feels fine when i click' copy' and have to tick the copy box but then I really  i need a pop up hint or something to remind me to click copy selected. Could we add this?

Land use
1. Can we swap the ' dwelling' blue colour (as this is too dark to be satisfying to colour in and likely comprise over 90% of entries) with the turquoise representing 'community services'
2. Can we put dwellings as the default at the top of the dropdown and then everything else  alphabetical
3. Can we change text in land use box to read' start typing to view options' as we need an instruction here to get them to put something in.
4. On the blue notice can this read ' Land use order, shown below, is automatically derived from the land use groups' i.e. adding 'shown below'   i know it sounds obvious but think no harm in making super clear as the word 'order' is not in common use.

Age 
1. Can we just go on with the original/current colour scheme for now and not release the one on staging as this still  needs more work

Save button- it would be really nice if we could just use return to save but this is for the next round -with the verification button. 

Could you possibly make the changes above and release next week? feels we are so nearly there!

**Comment by tomalrussell** [comment]
Noting more snags and queries, pulled over from #564 for future work:
- not sure if the two sets of squares (in the menu / in the sidebar) are needed? Might lead to confusion, e.g. the sidebar category links lead to view or edit depending on the mode, while the menu ones always lead to view etc.
- the sidebar squares have some problems with size/alignment and anti-aliasing (see picture, screenshot taken on Android but same happens on desktop Firefox)
- I've only seen this happen on Firefox, but when clicking on one of the sidebar categories, the appearing scrollbar causes the squares to overflow and the grid becomes a 4x3 instead of 3x4, taking even more vertical space
- the first two category squares in the last row (planning, sustainability) have swapped colors when comparing the logo (blue, green) to sidebar menu (green, blue)
- when coming onto the landing page, the empty white sidebar looks a bit out of place, gives the feeling of something unfinished. Maybe we could show the categories immediately?
- on mobile, there is no map zoom. It's possible to pinch-zoom on mobile, but that requires using two hands instead of one and unfortunately isn't very fluid with Leaflet on mobile web. I'd suggest keeping the zoom and search controls on all screen sizes
- awkward layout on mid-sized screens (700-1000px) - try narrower sidebar
- more spacing between category squares
- white background/whitespace instead of coloured bar "Age"/etc. when viewing/editing a particular building

**Comment by dining-liu** [comment]
Feel free to check the documentation and links to output tables -- [Webpage](https://github.com/colouring-london/colouring_london_analysis/tree/OS_landuse/OS_landuse).

**Comment by polly64** [comment]
Polly Hudson

Senior Research Fellow

Director - Colouring London https://colouringlondon.org/

Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ


No response to this email is presumed outside standard working hours.



________________________________
