### ISSUE TITLE
USER ENGAGEMENT & HOW TO USE SITE VIDEO

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#619]
Live to-do checklist for  @dining-liu  to work on with PH. @dominijk @MeldaS thoughts of course v. welcome on this at any time

1. [ ] Prepare user friendly  technical info page ready for upload #38
2. [ ] Create short how-to use this site animation using open software and able to be easily added to /adjusted over time
3. [ ] Test usability of sign-up and code of conduct make recommendations for improvements if required #391 
4. [ ] Make recommendations for simplification of discussion page #270
5. [ ] Prepare new leaderboards spec  TR for schools, historic environment bodies, commercial sector #48
6. [ ] Prepare first draft  for blog page to announce new features as grants (as rec by TR)
7. [ ] Create  copyright free diagrams for roof forms and typologies for the 'Size and shape' category'  to add to dropdown 
8. [ ] Prepare design for Showcase page as #571 
9. [ ] Show stats (see Dom) to allow easy measurement for funders/interest parties on user numbers #65
10. [ ] Look at issue os schools sign up and under 13 sign up with guardian to discuss with TR  #385
11. [ ] Sign up for ODI endorsement #528 and add ODI landbook #482
12. [ ] Work with PH and LJ to improve elegance of page design #495
13. [ ] Look at if we can collect _optional_  information on kinds of groups users are coming from to ensure we including as wide an audience as possible. I think this is best done perhaps when signing up for leaderboard 

#467

**Comment by dining-liu** [comment]
- To view software options to make explainer video, the storyboard of our "How to Use the Site" video, and some examples of PowerPoint animations, please check this [PPT file](https://1drv.ms/p/s!Apm6_BDKJjHJiL4QUkhi5Lpj89UT9A?e=WO4xf4).

- The first version of "How to Use the Site" video (adjusted to 1'30'') are listed in two formats: (1) Original PPT [file;](https://1drv.ms/p/s!Apm6_BDKJjHJiZR278VlQay8F6-RvQ?e=HwQAgU) (2) Exported [MP4](https://1drv.ms/v/s!Apm6_BDKJjHJiZR4AqUZ1-Wxh3lwkg?e=MecuuU).

**Comment by polly64** [comment]
hi @dining-liu brilliant  thanks could u possible load screenshots of the slides from the film  into this thread. I can then make comments under each one

**Comment by dining-liu** [comment]
- Added Alan Turing logo and put the updated file into [the shared dropbox folder](https://www.dropbox.com/sh/xmv40761z5yo8j7/AABHv3vAW95qB8XkxtRl3Ce2a?dl=0) named "ColouringLondon_UserEngagement" which includes all related work files ordered by date. 

- You can go directly to [this link](https://www.dropbox.com/s/j2thmq7b63wuox8/201017_HowToUseSite_video_addATlogo.pptx?dl=0) to view or download the updated ppt. 

Please notice our logo on first and last page are in the format of GIF (changing color automatically) recorded from our website, so the colors you see from the slides are just the snapshots of the GIF. 

Below are the screenshots, feel free to make comments on that:
**Slide 1** (Welcome page, introduce who we are)
![image](https://user-images.githubusercontent.com/56613839/96324600-31480480-1055-11eb-95c0-e0b034d991fb.png)

**Slide 2** (Introduce what we do)
![image](https://user-images.githubusercontent.com/56613839/96324522-ceef0400-1054-11eb-9883-d5c97504b94e.png)

**Slide 3** (Encourage people to sign up)
![image](https://user-images.githubusercontent.com/56613839/96324563-fe057580-1054-11eb-84a6-d93cb199ccaa.png)

**Slide 4** (How to sign up -- step ①:  how to access to our website)
![image](https://user-images.githubusercontent.com/56613839/96324648-72d8af80-1055-11eb-95f7-1bd8270afb43.png)

**Slide 5** (How to sign up -- step ②:  how to access to the sign-up page on the site)
![image](https://user-images.githubusercontent.com/56613839/96324629-5c325880-1055-11eb-931b-4731a21b996e.png)

**Slide 6** (How to sign up -- step ③:  how to fill in the sign-up form - a) an overview)
![image](https://user-images.githubusercontent.com/56613839/96324766-fdb9aa00-1055-11eb-82f9-5171437a0fac.png)

**Slide 7** (How to sign up -- step ③:  how to fill in the sign-up form - b) the upper half, recommend username naming convention)
![image](https://user-images.githubusercontent.com/56613839/96324858-686ae580-1056-11eb-8fa5-cc24de94c78f.png)

**Slide 8** (How to sign up -- step ③:  how to fill in the sign-up form - c) the lower half)
![image](https://user-images.githubusercontent.com/56613839/96325123-de238100-1057-11eb-8845-1ecb5bd06587.png)

**Slide 9** (Successfully registered, you can now start colouring!)
![image](https://user-images.githubusercontent.com/56613839/96325160-378bb000-1058-11eb-9b3f-65090b8a87ec.png)

**Slide 10** (You can contribute on building data of 12 categories. Let's take one category "Original Use" for example)
![image](https://user-images.githubusercontent.com/56613839/96325181-69047b80-1058-11eb-841f-8d43d4c3b681.png)

**Slide 11** (How to edit and view the data of one selected building)
![image](https://user-images.githubusercontent.com/56613839/96325258-f778fd00-1058-11eb-8836-a1b4dce9dad2.png)

**Slide 12** (Thank you page)
![image](https://user-images.githubusercontent.com/56613839/96325348-a3bae380-1059-11eb-8adb-ae6c257856bb.png)

**Comment by dining-liu** [comment]
### Video music
The music I used was Clear Sky from a Japanese animation. Considering the copyright issue, I find this music library for explainer video useful, free and safe to use forever:
https://www.yummy-sounds.com/explainer-video-music/#:~:text=On%20the%20other%20hand%2C%20some%20explainer%20videos%20use,inspire%20a%20cheerful%20vibe%20in%20their%20service%20explainer.

**Comment by polly64** [comment]
brillaint thanks - my daughter loved it!


Polly Hudson

Senior Research Fellow Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ


Research Fellow, The Alan Turing Institute

Director - Colouring London https://colouringlondon.org/


No response to this email is presumed outside standard working hours.



________________________________

**Comment by polly64** [comment]
ppt revisions including logos sent by email
