### ISSUE TITLE
Facilitate building attribute data upload for Community

### ISSUE THREAD

**Issue by edwardchalstrey1** [colouring-cities/colouring-core#734]
@matkoniecz @edwardchalstrey1  CLHEAG PRIORITY

The main purpose of the category is to:
- identify the type of buildings viewed as being of value to local communities and provide  relevant geospatial data for analysis 
- raise awareness of building threatened with demolition
- track/quantify the scale of loss/additions of community assets over time
- quantify and geolocate all buildings in non-profit ownership in the city 
- provide a tool to allow communities to change demolition of important local buildings

Actions required

- [ ] Allow to save edits, doesn't currently work https://github.com/colouring-cities/colouring-london/issues/734#issuecomment-1025690548
- [x] Remove  the 'x people like this building' x 2 completely 
- [x] Change the question 'Do you think this building should be recorded as one of special local significance?' to read 'Do you think this building should be recorded as a local heritage asset? (add x ticks)
- [ ]  Add new subcategory  'Is this building already registered as being of local or national significance?'
Yes/No 
- [ ] Add link to Planning category add info on Planning category (do this one later)
- [x] Change 'Can you help add information about public ownership of the building' to 'Can you help add information on community use of buildings?'
- [x] Change the title to  'Is building in some sort of "community" ownership'" Yes/No (covered by #774)
- [x] Change above dropdown wording from 'state-owned' to 'government owned'
- [x] Add 'Are activities open to the community currently taking place in the building?' Yes/No  (covered by #774)
- [x] Add 'Has the building always been used for community activities?' Yes/No  (covered by #774)
- [x] Add 'Has the building ever been used in the past for community activities, but isn't now? Yes/No  (covered by #774)

#773 (comment)

- [ ] #773
- [ ] Add copy tool 

For history see also closed issue #602

**Comment by polly64** [comment]
The main purpose of the category is to:
a)  identify the type of buildings viewed as being of value to local communities and provide  relevant geospatial data for analysis 
b)  raise awareness of building threatened with demolition
c)  track/quantify the scale of loss/additions of community assets over time
d) quantify and geolocate all buildings in non-profit ownership in the city 






see also closed issues

**Comment by matkoniecz** [comment]
@polly64 

> Change the 'x people like this building' to not include 0 likes.

Can be done but not entirely sure is it improving consistency of interface.

>  Change the 'x people like this building to '2 ticks' not '2 likes')

Are you sure that it will be as clear as likes? I am not a English native speaker but at least to me the first association was [a parasite](https://en.wikipedia.org/wiki/Tick)

I am not fan of a FB et all, but I think it may be useful to keep standard terminology.

(it is entirely clear that I am wrong, feel free to discount my opinion on preferred phrasing in the English language as I have limited experience with it - on the other hand it is also used by people outside UK who are not necessarily native speakers of English...)

>  Allow to save edits, doesn't currently work

To be more specific:

liking building works without saving

Answering "Do you think this type of building is generally worth keeping?" edit is without reaction, saving silently fails.

Answering "Has the building ever been used for community activities?" actually requires saving and actually works.

Answering both questions also works.

Answering "Has the building ever been used for community activities?", not saving answering "Do you think this type of building is generally worth keeping?" shows a confusing error message.

**Comment by matkoniecz** [comment]
Conclusion:

remove

> 0 people so far think this building should be classified as a locally listed heritage asset

> 3 people like this building

as info in this format is easy to misintepret and this info is accessible in the edit hostory

**Comment by polly64** [comment]
PH additional comment - removal of 'likes number is necessary as implies people do not like a building (commonly someone's home) when in fact means no comment has been made.  The range of likes is also shown on the key, and the actual number can be tracked on the edit history NB this feature is used primarily for engagement and as a tool/visual evidence of opposition by  local communities of demolition of local assets. It cannot be used in statistical analysis until the issue with multiple OS MasterMap polygons being assigned to single addresses has been resolved - at present we have not found a solution to this

**Comment by matkoniecz** [comment]
>  Change the question 'Do you think this building should be recorded as one of special local significance?' to read 'Do you think this building should be recorded as a local heritage asset? (add x ticks)

It is a bit inconsistent and may be worth changing how it is referred in code `building.community_local_significance` but it is not actively misleading and would be quite irritating. I think I will change just label to have one simple thing for once.
