### ISSUE TITLE
Add items to 'Age' category (for top milestones)

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#865]
Add 

- [ ] Extension date/s - and for each extension date have source 
- [ ] Refurbishment date/s + source
- [ ] date of cladding (where added later)+ source
- These dates should link to Team  section so that info on teams for each can also be collected :

Under 'Team' for extension date  and refurbishment date- add options for 'architect' and 'builder' and source
For cladding- 'installer'
