### ISSUE TITLE
Ed -> Mike handover checklist

### ISSUE THREAD

**Issue by edwardchalstrey1** [colouring-cities/colouring-core#891]
Key links for Mike to bookmark:

- The site: https://colouringlondon.org/
- Polly’s manual for the CCRP: https://github.com/colouring-cities/manual/wiki/A.Overview-and-research-questions
- Repo containing scripts we use in the Azure VM hosting production version of Colouring London (the website): https://github.com/colouring-cities/colouring-london-config

Ed TODOs:

- [x] Figure out whether Turing can keep providing Azure credits
- [x] Invite Mike and Polly to the CL Azure subscription
    - [x] Return IT policy to get Mike added after he and Polly sign
- [x] Add Mike's public key to Azure VMs
- [x] Make sure Mike has correct GitHub access rights
- [x] Teach @polly64 to request new credits to CL subscription - it sounds like @mdsimpson42 will not be able to do this, since he is not a Turing employee and this will need to be done via the intranet
- [x] Document the database saving process for CL
    - [x] Check that daily syncs to blob storage works

@mdsimpson42: TODOs

- [x] Return Turing IT Policy after yourself and Polly have signed (for Azure)
- [x] Check you then have access to CL Azure subscription
- [x] Send Ed public key to add to Azure VMs
- [x] Check you can ssh into VMs (but also see if substituting `mikesimpson` for `cladmin` works):
    - `ssh -i <private key path> mikesimpson@cl-staging.uksouth.cloudapp.azure.com`
    - `ssh -i <private key path> mikesimpson@cl-production.uksouth.cloudapp.azure.com`
- [x] Can set up a local VM for CL dev work: Setup doc for a local version of Colouring London: https://github.com/colouring-cities/colouring-london/blob/master/docs/setup-dev-environment.md
- [x] Check able to make changes to https://colouringlondon.org/ - a good first issue:
    - [x] Add Newcastle logo to website homepage
- [x] Add self to contributors list on GH via the contributors bot (take a look how this was done before)
- [x] Decide whether to continue Ed's project board or start fresh
    - Could continue @edwardchalstrey1 progress for #892 PR: #896 - but may wish to work on #815 first

**Comment by edwardchalstrey1** [comment]
Hi @mdsimpson42 don't worry about these items right now, I'm just making a list ahead of our chat next week

**Comment by polly64** [comment]
@edwardchalstrey1 thanks

**Comment by edwardchalstrey1** [comment]
Just to update you both on the database backup situation: the database is being saved and backed up daily, with copies older than 6 days being deleted. Sorry for causing any confusion on this Polly, but there's no problem!
@mdsimpson42, once you are set up on Azure, you can download a recent copy of the database for use on your local instance of Colouring London. This is what I did when I got started - documented under "Create database from dump" as part of the [local setup instructions](https://github.com/colouring-cities/colouring-london/blob/master/docs/setup-dev-environment.md#house-loading-the-building-data)

**Comment by mdsimpson42** [comment]
@edwardchalstrey1 I've set up access to the Turing, and can confirm that I can access the SharePoint folder! 👍
